export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  BATCH_NOT_FOUND: "BATCH_NOT_FOUND",
  BATCH_CLOSED: "BATCH_CLOSED",
  BATCH_EMPTY: "BATCH_EMPTY"
} as const;
